version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      #- docker login -u AWS -p $(aws ecr get-login-password --region $AWS_DEFAULT_REGION)
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build . -t $IMAGE_REPO_NAME:$IMAGE_TAG --build-arg GIT_API_TOKEN=$GIT_API_TOKEN --build-arg OPENSTUDIO_VERSION=$OPENSTUDIO_VERSION --build-arg OS_STANDARDS_BRANCH=$OS_STANDARDS_BRANCH --build-arg OS_STANDARDS_ORG=$OS_STANDARDS_ORG --build-arg ENABLE_RSMEANS=$ENABLE_RSMEANS --build-arg WEATHER_FILES="$WEATHER_FILES --build-arg LOCAL_COSTING_PATH=$LOCAL_COSTING_PATH"
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

# test command locally.
# docker build -t test_me:test_tag --build-arg GIT_API_TOKEN=<your_token> --build-arg OPENSTUDIO_VERSION=3.0.1 --build-arg OS_STANDARDS_BRANCH=nrcan .