:compute_environment: local_docker
:datapoint_image_configuration:
  :nocache: false
  :dockerfile_folder: btap_cli
  :dockerfile_url: https://raw.githubusercontent.com/canmet-energy/btap_cli/dev/Dockerfile
  :image_build_args:
    IMAGE_REPO_NAME: btap_cli
    OPENSTUDIO_VERSION: 3.2.1
    BTAP_COSTING_BRANCH: master
    OS_STANDARDS_BRANCH: nrcan
  :job_configuration:
    :container_command: bundle exec ruby btap_cli.rb
    :container_input_path: /btap_costing/utilities/btap_cli/input
    :container_output_path: /btap_costing/utilities/btap_cli/output
