---

# Branch of btap_batch to be used in aws_batch_analysis compute_environment runs on AWS.
btap_batch_branch: dev

# Branch of btap_costing to build used in environment
btap_costing_branch: master

# Branch of openstudio-standards used in environment
os_standards_branch: nrcan

# Branch of openstudio version to build into container environment. This by default will select the E+ version used with that version.
openstudio_version: 3.6.1

weather_list: [
  'CAN_QC_Montreal-Trudeau.Intl.AP.716270_CWEC2016.epw',
  'CAN_NS_Halifax.Dockyard.713280_CWEC2016.epw',
  'CAN_AB_Edmonton.Intl.AP.711230_CWEC2016.epw',
  'CAN_BC_Vancouver.Intl.AP.718920_CWEC2016.epw',
  'CAN_AB_Calgary.Intl.AP.718770_CWEC2016.epw',
  'CAN_ON_Toronto.Pearson.Intl.AP.716240_CWEC2016.epw',
  'CAN_NT_Yellowknife.AP.719360_CWEC2016.epw',
  'CAN_AB_Fort.McMurray.AP.716890_CWEC2016.epw'
]
disable_costing: False