
type: object
properties:
  build_env_name:
    description: ":Prefix used to identify images, folders and other items specific to a build environment. Only 
    lowercase, numbers and underscore and <24 chars."
    type: string
    pattern: ^[a-z0-9_\\s]*$
    minLength: 1
    maxLength: 24

  git_api_token:
    description: "The authorization token to access Github. You are required to have a github account and generate a 
    classic personal access token. Instructions to generate one are 
    [here](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens)"
    type: string

  btap_batch_branch:
    description: "Branch of btap_batch to use to build environment. For general users the 'main' branch should be used. 
    You can review available branches [here](https://github.com/canmet-energy/btap_batch) if you are a developer. "
    type: string

  os_standards_org:
    description: "**ADVANCED** The GitHub organization name containing the OpenStudio-standards repository. This is the fork used to build the btap_cli environment. 
    The default is NREL."
    type: string
    default: NREL

  os_standards_branch:
    description: "Branch of NREL's Openstudio-standards repository to use to build environment. The default branch to use is 'nrcan' This 
    branch is only accessible for authorized users. You can review available branches
    [here](https://github.com/nrel/openstudio-standards)"
    type: string
    default: nrcan

  openstudio_version:
    description: "Valid version of the OpenStudio SDK to build with."
    type: string
    enum:
      - 3.6.1
      - 3.7.0

  btap_weather:
    description: "Location of weather files to download. If true, downloads from [btap_weather](https://github.com/canmet-energy/btap_weather). Else, downloads from Climate.OneBuilding.Org."
    type: boolean
    default: true

  weather_list:
    description: "List of Weather files to build included in the build environment. Only .epw files , and <100 files. 
    Other weather locations are available. However, you have to define the ones you want to use when creating your 
    environment.  The other locations that you can use can be found in [here](https://climate.onebuilding.org/)\n\n 

    Here is an example:\n\n"

    examples: [
    weather_list: [
      "CAN_QC_Montreal.Intl.AP.716270_CWEC2020.epw",
      "CAN_NS_Halifax.Dockyard.713280_CWEC2020.epw",
      "CAN_AB_Edmonton.Intl.AP.711230_CWEC2020.epw",
      "CAN_BC_Vancouver.Intl.AP.718920_CWEC2020.epw",
      "CAN_AB_Calgary.Intl.AP.718770_CWEC2020.epw",
      "CAN_ON_Toronto.Intl.AP.716240_CWEC2020.epw",
      "CAN_NT_Yellowknife.AP.719360_CWEC2020.epw",
      "CAN_AB_Fort.Mcmurray.AP.716890_CWEC2020.epw"
      ]
    ]
    items:
      type: string
      pattern: ^.*\.epw$
    minItems: 1
    maxItems: 100

  enable_rsmeans:
    description: "**ADVANCED** for NRCan use only."
    type: boolean
    default: false

  local_costing_path:
    description: "Path to the local costing_database.json costing file.  The default is '<this btap_batch local repository location>/resources/costing/costing_database.json'. If you are using a custom costing file, you can set the path. here\n\n
    Ignore this if you are not using costing or content with the default costing_database.json costing file.\n\n"
    type: string
    default: resources/costing/costing_database.json

  build_btap_cli:
    description: "**ADVANCED** Build most recent btap_cli always. Set to false to save time if standards and costing branches have not changed."
    type: boolean
    default: true

  build_btap_batch:
    description: "**ADVANCED** Build most recent btap_batch always. Set to false to save time if standards and costing branches have not changed."
    type: boolean
    default: true

  local_nrcan:
    description: "**NRCan only** Set this to True if you intend to build your environment locally on a computer connected to 
    the NRCan network.  Otherwise leave it as False."
    type: boolean
    default: false

  compute_environment:
    description: "Select which environment to build and where to run analyses.\n\n 
    **local**: will use docker on your local computer.\n\n
    **aws**: will manage and run eveything on AWS. You can turn off your local computer after the analysis is submitted\n\n
    **local_managed_aws_workers**: **ADVANCED** will manage the analysis on a local computer and run the simulations on aws.\n\n 
    "
    type: string
    enum:
      - local
      - local_managed_aws_workers
      - aws

required:
  - build_env_name
  - git_api_token
  - btap_batch_branch
  - os_standards_org
  - os_standards_branch
  - openstudio_version
  - weather_list
  - enable_rsmeans
  - local_costing_path
  - build_btap_cli
  - build_btap_batch
  - local_nrcan
  - compute_environment
additionalProperties: false


